Repository meanvoid/nix-flakes, pull requests merged in 2023-04, with the labels that each got.

#5 Merge to master changes
  .github/workflows/build.yml
  .github/workflows/update.yml
  derivations/darwin/steam.nix
  derivations/nixos/default.nix
  flake.lock
  flake.nix
  host/darwin/.DS_Store
  host/darwin/home-manager/steam/default.nix
  host/home-server/default.nix
  host/home-server/hardware-configuration.nix
  hosts/darwin/default.nix
  hosts/darwin/macmini/configuration.nix
  hosts/darwin/macmini/home-manager/home.nix
  hosts/darwin/macmini/home-manager/imports.nix
  hosts/darwin/macmini/home-manager/programs.nix
  hosts/linux/default.nix
  hosts/linux/unsigned-int32/configuration.nix
  hosts/linux/unsigned-int32/hardware-configuration.nix
  hosts/linux/unsigned-int32/home/ashuramaru/home.nix
  hosts/linux/unsigned-int32/home/default.nix
  hosts/linux/unsigned-int32/home/meanrin/home.nix
  hosts/linux/unsigned-int64/configuration.nix
  hosts/linux/unsigned-int64/hardware-configuration.nix
  hosts/linux/unsigned-int64/networking/networking.nix
  hosts/linux/unsigned-int64/networking/proxy.nix
  hosts/linux/unsigned-int64/networking/wireguard/wg-ports0.nix
  hosts/linux/unsigned-int64/networking/wireguard/wireguard.nix
  hosts/linux/unsigned-int64/networking/wireguard/wireguard0.nix
  hosts/linux/unsigned-int64/services/nextcloud/nextcloud.nix
  hosts/linux/unsigned-int64/services/services.nix
  hosts/linux/unsigned-int64/services/vaultwarden/vaultwarden.nix
  hosts/linux/unsigned-int64/ssh/authorizedKeys_ashuramaru.keys
  modules/containers/minecraft.nix
  modules/networking/default.nix
  modules/networking/proxy/proxy.nix
  modules/networking/vpn/openvpn/opvn.nix
  modules/networking/vpn/wireguard/wg.nix
  modules/networking/wireguard.nix
  modules/overlays/default.nix
  modules/overlays/discord.nix
  modules/powermanagment/hddparm.nix
  modules/programs/games.nix
  modules/programs/nodejs.nix
  modules/programs/packages.nix
  modules/programs/spotify.nix
  modules/services/flatpak.nix
  modules/services/fonts.nix
  modules/services/jellyfin.nix
  modules/services/media/jellyfin.nix
  modules/services/nas/samba.nix
  modules/services/samba.nix
  modules/services/utils/flatpak.nix
  shells/cuda.nix
Labels: enhancement

#8 Fixed outputs
  hosts/darwin/default.nix
  hosts/linux/default.nix
  hosts/linux/unsigned-int64/configuration.nix
Labels: enhancement, help wanted

#14 Remove space from ACCESS_TOKEN
  .github/README.md
  .github/workflows/build.yml
  .github/workflows/tests.yml
  .github/workflows/update.yml
  .github/workflows/validate.yml
  hosts/linux/unsigned-int64/networking/wireguard/wg-ports0.nix
  modules/networking/vpn/wireguard/wg.nix
Labels: bug, enhancement

#16 Boot
  flake.lock
  flake.nix
  hosts/linux/default.nix
  hosts/linux/unsigned-int32/configuration.nix
  hosts/linux/unsigned-int32/hardware-configuration.nix
  hosts/linux/unsigned-int32/home/ashuramaru/_.env.nix
  hosts/linux/unsigned-int32/home/ashuramaru/home.nix
  hosts/linux/unsigned-int32/home/default.nix
  hosts/linux/unsigned-int64/configuration.nix
  hosts/linux/unsigned-int64/networking/proxy/proxy.nix
  hosts/linux/unsigned-int64/networking/wireguard/wg-ports0.nix
  hosts/linux/unsigned-int64/networking/wireguard/wireguard0.nix
  hosts/linux/unsigned-int64/services/nextcloud.nix
  modules/overlays/discord.nix
  modules/powermanagment/hddparm.nix
  modules/programs/default.nix
  modules/programs/dev/nodejs.nix
  modules/programs/dev/vim.nix
  modules/programs/dev/vscode.nix
  modules/programs/games.nix
  modules/programs/packages.nix
  modules/programs/spotify.nix
  modules/programs/utils/bashrc.nix
  modules/programs/utils/git.nix
  modules/programs/utils/gpg.nix
  modules/programs/utils/utils.nix
  modules/programs/utils/zshrc.nix
  modules/server/default.nix
  modules/services/nas/samba.nix
  secrets/secrets.nix
  secrets/wireguard-server-shared_julio.age
Labels: enhancement
